" minimal subset of my vimrc file

" VIM not VI
set nocompatible

" map Ctrl-C: save and quit
map! <C-C> <ESC>:wq<CR>
map  <C-C> :wq<CR>

" escape is far away
map! <C-L> <ESC>

" 4 is enough
set tabstop=4
set shiftwidth=4
" backspace should consume 4 spaces
set softtabstop=4

" replace tabs with space (Python must)
set expandtab

" be clever!
set smartindent

" syntax coloring
syntax on

" backspace consumes!
set backspace=2

" scroll before end of screen
set scrolloff=4

" incremental search
set incsearch

" ignore case unless search has mixed case
set smartcase

" some sinful emacs bindings
map! <C-K> <C-O>D
map! <C-A> <C-O>0
map! <C-E> <C-O>$


" open files where you left offf
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" writing out System.out.printf is too painful
au BufRead,BufEnter *.java iabbr sysf System.out.printf(""<Left>


"
" F-keys
"

" no formatting of preformatted text (copy-n-paste)
set pastetoggle=<F3>

" map F8: toggle line numbers
map <F8> :set number!<CR><Bar>:echo "line numbers: " . strpart("OffOn", 3 * &number, 3) <CR>

" make invisible characters visible
set listchars=eol:␤,tab:>-,trail:®,extends:>,precedes:<,nbsp:¤

" map F9: toggle invisible
map <F9> :set list!<CR>
