# Handy aliases
alias x='xterm&'
alias sshuio='ssh bjarneh@login.ifi.uio.no'
alias sshntnu='ssh bjarhole@login.ansatt.ntnu.no'
alias sshgw='ssh bjarhole@sshgw.it.ntnu.no'
alias sshdbdev_out='ssh dbdev@195.18.225.138'
alias sshdbdev='ssh dbdev@10.20.62.14'
alias sshresman_out='ssh resman@195.18.225.139'
alias sshresman='ssh resman@10.20.62.15'
alias vpnresman='sudo openconnect --protocol=gp vpn.resman.no'
alias sshazure_resadmin_global_prod='ssh resadmin@res-resbase-vm1.westeurope.cloudapp.azure.com'
alias sshazure_resadmin_global_test='ssh resadmin@res-resbase-vm2.westeurope.cloudapp.azure.com'
alias sshazure_resadmin_local_prod='ssh resadmin@172.18.5.5'
alias sshazure_resadmin_local_test='ssh resadmin@172.18.5.6'
#alias sshazure_Resbaseadmin_local_prod='ssh Resbaseadmin@172.18.5.5'
#alias sshazure_Resbaseadmin_local_test='ssh Resbaseadmin@172.18.5.6'
alias sl='ls'
alias rdeskconceptos='rdesktop -u bjarne@local.conceptos.no -r disk:/home/bjarneh/mercurial/mine/conceptos/docx -g 1600x1000 remote.conceptos.no'
alias rdeskasn='rdesktop -u bjarne.holen@amestocloud.com -r disk:/home/bjarneh/mercurial/mine/conceptos/docx -f asn-1070-01.westeurope.cloudapp.azure.com'
alias rdeskasn3='rdesktop -u bjarneholen -r disk:/home/bjarneh/mercurial/mine/conceptos/docx -f bjarneholen003.westeurope.cloudapp.azure.com'
alias rdeskasn4='rdesktop -u bjarneholen -r disk:/home/bjarneh/mercurial/mine/conceptos/docx -f bjarneholen004.westeurope.cloudapp.azure.com'
alias xfreerdpasn='xfreerdp /f /u:bjarne.holen@amestocloud.com /v:asn-1070-01.westeurope.cloudapp.azure.com:3389'
alias sincewakeup="journalctl -n 1 -o short-iso -b 0 -t kernel MESSAGE='PM: Finishing wakeup.'"
alias openports='sudo netstat -tuvnlp'

## Functions that cannot be separate scripts
mkcd(){ [ -n "$1" ] && mkdir -p "$1" && cd "$1"; }
mvcd(){ [ -f "$1" ] && [ -d "$2" ] && mv "$1" "$2" && cd "$2"; }
